### ISSUE TITLE
Compiled against the ABI-stable Node.js API (N-API) error

### ISSUE THREAD

**Issue by claycolonna** [dashersw/wits#1]
Keep getting this error:

App threw an error during load
Error: The module 'PATH/node_modules/wits/build/Release/emotiv.node'
was compiled against the ABI-stable Node.js API (N-API).
This feature is experimental and must be enabled on the 
command-line by adding --napi-modules.

Does this have to do with the version of Node.js I'm running?

Thanks

**Comment by claycolonna** [comment]
It had to do with the node versioning in my electron build. Sorry to waste your time

**Comment by dashersw** [comment]
No worries! Happy that it was an easy fix for you!

**Comment by nileshbandekar** [comment]
What is the solution to this type of issue? @claycolonna

**Comment by dashersw** [comment]
@nileshbandekar probably making sure to use node v10?
